title: Cyber HackPath
description: Tu Inicio en el Mundo del Hacking y la Ciberseguridad
author: Wil Leonardo
show_downloads: false
google_analytics: G-VQFMX46E9C
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-seo-tag