title: Cyber HackPath
author: Wil Leonardo
description: Tu Inicio en el Mundo del Hacking y la Ciberseguridad
show_downloads: false
google_analytics: G-VQFMX46E9C
paginate: 1
paginate_path: "/cyber/page:num/"
theme: jekyll-theme-hacker